// Generated by Hexa https://hexalang.github.io
// RAM
// LICENSE LGPL-3.0
;(function() {
	"use strict"
	const $global = typeof(window) === "undefined"? global : window
	if (typeof($global.require) === "undefined") { $global.require = function () {} };
	var console_73 = $global.console
	function hasOwnProperty(object_107, name_108) { return object_107.hasOwnProperty(name_108) };
	{
		{
			window.window.document.getElementById('test').onclick = () => {
				console.log('Engage!');
				const bytes = (1024 * 1024 * 1024 * 1) || 0;
				const half_of_elements = ((bytes) / 8) / 2;
				const gigabyte = 134217728;
				const two_gigabyte = 268435456;
				const view = new Float64Array(two_gigabyte - 2);
				view.fill(123);
				view.fill(234);
				console.log(view.length);
				let best = 9999;
				{
					let i = 0;
					while (i < 20) {
						const begin = Date.now();
						view.copyWithin(gigabyte, 0, gigabyte);
						const diff = Date.now() - begin;
						if (diff < best) { best = diff };
						i++;
					};
				};
				window.window.document.getElementById('results').innerHTML = ('<p><b>RAM Speed fill: 1 Gb in ' + (best) + 'ms at ' + Math.round((1 / ((best) / 1000)) * 1000 * 3) + ' megabytes per second</b></p>');
				console.log('Engines off!');
			};
		}
	}
})();
